from app.db.session import SessionLocal
from app.models.job import Category
from sqlmodel import Session

CATEGORY_KEYWORDS = {
    "Ugostiteljstvo I Turizam": [
        "konobar",
        "sobar",
        "barmen",
        "bartender",
        "kuvar",
        "kuha",
        "kuhinja",
        "chef",
        "pastry",
        "poslastič",
        "recepcioner",
        "reception",
        "front desk",
        "housekeeping",
        "spasilac",
        "horeca",
        "hotel",
        "restoran",
        "turizam",
        "guest",
        "gost",
        "kelner",
        "pomoćni kuvar",
        "šef kuhinje",
    ],
    "Prodaja I Maloprodaja": [
        "prodavac",
        "prodaj",
        "sales",
        "trgovac",
        "trgovin",
        "merchandiser",
        "komercijalista",
        "komercij",
        "agent prodaje",
        "maloprodaj",
        "drogerij",
        "prodavnic",
        "shop",
        "retail",
        "cashier",
        "blagajnik",
    ],
    "Vožnja, Transport I Logistika": [
        "vozač",
        "driver",
        "vož",
        "taxi",
        "dostavljač",
        "dostav",
        "prevoz",
        "magacioner",
        "magacin",
        "warehouse",
        "skladišt",
        "logist",
        "pakirnic",
        "pakova",
        "dispatcher",
        "kurirsk",
    ],
    "Administracija I Uredski poslovi": [
        "referent",
        "administrativ",
        "office",
        "asistent",
        "admin",
        "sekretar",
        "šalter",
        "uredsk",
        "clerk",
        "data entry",
        "dokumentacij",
        "arhiv",
        "registrat",
        "kancelarij",
        "protocol",
    ],
    "Finansije I Računovodstvo": [
        "računovođa",
        "računovodstv",
        "accountant",
        "accounting",
        "finansij",
        "bookkeeper",
        "knjigovođa",
        "reviz",
        "audit",
        "buxhalter",
        "financ",
        "platni promet",
        "billing",
    ],
    "Obrazovanje": [
        "nastavnik",
        "profesor",
        "učitelj",
        "vaspitač",
        "vaspitanj",
        "teacher",
        "edukator",
        "tutor",
        "instruktor",
        "škol",
        "predavač",
        "odgajatelj",
        "pedagog",
        "obrazovan",
    ],
    "Zdravstvo I Medicina": [
        "doktor",
        "ljekař",
        "medicin",
        "nurse",
        "medicinska sestra",
        "specijalist",
        "zdravstv",
        "bolnic",
        "clinic",
        "ambulant",
        "terapeut",
        "farmaceut",
        "apoteka",
        "dental",
        "hirurg",
    ],
    "Građevina I Inženjerstvo": [
        "građevin",
        "inženjer",
        "engineer",
        "civil",
        "nadzor",
        "arhitekt",
        "projektant",
        "majstor",
        "zidar",
        "bravar",
        "keramičar",
        "fasader",
        "construction",
        "elektro",
        "instalat",
        "tehničk",
        "zavariv",
        "welder",
    ],
    "Menadžment I Liderstvo": [
        "direktor",
        "manager",
        "menadžer",
        "rukovodil",
        "šef",
        "head",
        "supervisor",
        "koordinator",
        "team lead",
        "principal",
        "general manager",
        "izvršni",
        "voditelj",
        "chief",
    ],
    "HR I Ljudski resursi": [
        "hr",
        "human resources",
        "kadrov",
        "ljudsk resursi",
        "people",
        "recruiter",
        "regrutac",
        "talent",
        "zapošljavanj",
        "personalni",
    ],
    "Marketing I Komunikacije": [
        "marketing",
        "pr",
        "komunikacij",
        "social media",
        "content",
        "digital",
        "advertising",
        "oglašava",
        "brand",
        "promotion",
        "kreativ",
        "copywriter",
        "seo",
        "medij",
    ],
    "IT I Tehnologija": [
        "developer",
        "programmer",
        "software",
        "it",
        "tech",
        "system",
        "network",
        "admin",
        "web",
        "programer",
        "code",
        "qa",
        "tester",
        "devops",
        "data",
        "analyst",
        "cyber",
        "informatič",
    ],
    "Pravni poslovi": [
        "pravnik",
        "advokat",
        "legal",
        "lawyer",
        "sudski",
        "notarski",
        "pravni",
        "legislation",
        "compliance",
        "paralegal",
        "sud",
    ],
    "Proizvodnja I Industrija": [
        "proizvod",
        "radnik",
        "operator",
        "production",
        "fabrik",
        "postrojenj",
        "manufaktur",
        "assembly",
        "montaž",
        "worker",
        "machine operator",
        "industrijski",
        "tehnolog",
    ],
    "Usluge I Zanatstvo": [
        "frizer",
        "frizersk",
        "beauty",
        "kozmetič",
        "salon",
        "zanatski",
        "majstor",
        "servis",
        "maintenance",
        "održavanj",
        "cleaning",
        "čistač",
        "security",
        "obezbeđenj",
        "čuvar",
    ],
    "Korisnička podrška": [
        "call cent",
        "customer service",
        "support",
        "korisnič",
        "operater",
        "help desk",
        "client",
        "telefon",
        "bpo",
    ],
}


def create_categories():
    session: Session = SessionLocal()

    for key in CATEGORY_KEYWORDS.keys():
        category = Category(name=key)
        session.add(category)
        session.commit()

    session.close()
