"""set expires to be None as default

Revision ID: 27cead27bfc4
Revises: 64c61f16e0c2
Create Date: 2026-01-29 08:11:18.972083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cead27bfc4'
down_revision: Union[str, Sequence[str], None] = '64c61f16e0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'expires',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'expires',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
