"""on job model set url to be unique

Revision ID: 64c61f16e0c2
Revises: 8120b679dbad
Create Date: 2026-01-28 16:41:07.572963

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '64c61f16e0c2'
down_revision: Union[str, Sequence[str], None] = '8120b679dbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_job_url', 'job', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_url', 'job', type_='unique')
    # ### end Alembic commands ###
