"""added description field

Revision ID: c4c2468bc136
Revises: e0d2cd167ab3
Create Date: 2026-02-27 14:24:02.901140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c4c2468bc136'
down_revision: Union[str, Sequence[str], None] = 'e0d2cd167ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'description')
    # ### end Alembic commands ###
